version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: dogplaybd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
