CREATE TABLE pet
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255),
    data_nascimento date,
    raca            VARCHAR(255),
    cor             VARCHAR(255),
    sexo            VARCHAR(255),
    id_dono         BIGINT,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE prestador
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preco       VARCHAR(255),
    passeador   VARCHAR(255),
    adestrador  VARCHAR(255),
    localizacao VARCHAR(255),
    CONSTRAINT pk_prestador PRIMARY KEY (id)
);

CREATE TABLE prestador_servico
(
    id_prestador BIGINT NOT NULL,
    id_servico   UUID   NOT NULL
);

CREATE TABLE servico
(
    id           UUID    NOT NULL,
    taxa         VARCHAR(255),
    preco        VARCHAR(255),
    localizacao  VARCHAR(255),
    endereco     VARCHAR(255),
    atividade    VARCHAR(255),
    hora_passeio INTEGER NOT NULL,
    CONSTRAINT pk_servico PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf      VARCHAR(255),
    nome     VARCHAR(255),
    email    VARCHAR(255),
    endereco VARCHAR(255),
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_ID_DONO FOREIGN KEY (id_dono) REFERENCES usuarios (id);

ALTER TABLE prestador_servico
    ADD CONSTRAINT fk_preser_on_prestador FOREIGN KEY (id_prestador) REFERENCES prestador (id);

ALTER TABLE prestador_servico
    ADD CONSTRAINT fk_preser_on_servico FOREIGN KEY (id_servico) REFERENCES servico (id);